name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp: ["26"]
        os: [ubuntu-latest]

    env:
      ZOTONIC_DIR: /tmp/zotonic
      ZOTONIC_VERSION: 1.0.0-rc.15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}

      - name: Install and configure Zotonic
        # run: git clone https://github.com/zotonic/zotonic.git $ZOTONIC_DIR --depth 1 --branch $ZOTONIC_VERSION
        run: git clone https://github.com/williamthome/zotonic.git $ZOTONIC_DIR --depth 1 --branch fix/bcrypt

      - name: Compile
        working-directory: ${{ env.ZOTONIC_DIR }}
        run: make
